const UILAYER = "ui-layer"
const BACKGROUNDLAYER = "background-layer"

const PEN = "pen"
const ERASER = "eraser"
const RECT = "rect"
const LINE = "line"
const CIRCLE = "circle"
const CLEAR = "clear"
const DOWNLOAD = "download"
const CANCEL = "cancel"
const REDO = "redo"
const TEXT = "text"
const COLOR = "color"